name: "Quest Assistant"
version: "0.1.0"
slug: "questassistant"
description: "A Quest tracking assistant for Home Assistant"
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
init: false
startup: "application"
boot: "auto"
webui: "http://[HOST]:[PORT:80]"
ports:
  80/tcp: 5000
